# Configuration for Coveralls.io
service_name: github

# Path to the Clover XML coverage report
coverage_clover: build/coverage.xml

# Root directory of the source code
src_dir: .

# Paths to exclude from coverage analysis
exclude_paths:
  - tests/
  - vendor/
  - '@tools/'
  - '@examples/'
  - '*.php' # Exclude root php files like exec.php, .php-cs-fixer.php
