# Root Project Configuration for SonarCloud

sonar.projectKey=Hubbitus_HuPHP
sonar.organization=hubbitus

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=HuPHP
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.

# Path to test files
sonar.tests=tests

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Paths to exclude from analysis
sonar.exclusions= \
  tests/**, \
  vendor/**, \
  @tools/**, \
  @examples/**, \
  build/**, \
  .github/**, \
  *.php

# Path to the coverage report
sonar.php.coverage.reportPaths=build/coverage.xml

# Ignore specific rules that conflict with the project's code style
sonar.issue.ignore.multicriteria=s1808,s103

# S1808: Move this open curly brace to the beginning of the next line. (Conflicts with PSR-12/PER Coding Style)
sonar.issue.ignore.multicriteria.s1808.ruleKey=php:S1808
sonar.issue.ignore.multicriteria.s1808.resourceKey=**/*.php

# S103: Lines should not be too long
sonar.issue.ignore.multicriteria.s103.ruleKey=php:S103
sonar.issue.ignore.multicriteria.s103.resourceKey=**/*.php
