name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, gd, xml, dom, zip, bz2
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Lint
        run: ./tests/lint.sh

      - name: Run Tests
        run: ./tests/run-tests.sh

      - name: Regenerate All
        run: bash ./.tools/regenerate.all

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: .tools/regenerate.all.log
          
  deploy-docs:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, gd, xml, dom, zip, bz2
          tools: composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Regenerate Docs
        run: bash ./.tools/regenerate.all

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './@phpdocs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
