name: Release

on:
  push:
    branches:
      - master
  issue_comment:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate version
        id: generate_version
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            VERSION="$VERSION-pr"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, gd, xml, dom, zip, bz2
          tools: composer
          ini-values: phar.readonly=0

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Regenerate All
        run: bash ./@tools/regenerate.all

      - name: Create Release for master
        if: github.event_name == 'push'
        id: create_release_master
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Master Release Asset
        if: github.event_name == 'push'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_master.outputs.upload_url }}
          asset_path: ./@tools/Packages/build/HuPHP.phar
          asset_name: HuPHP.phar
          asset_content_type: application/phar

      - name: Create Release for PR
        if: |
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          contains(github.event.comment.body, '/release') &&
          (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
        id: create_release_pr
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: true

      - name: Upload PR Release Asset
        if: |
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          contains(github.event.comment.body, '/release') &&
          (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_pr.outputs.upload_url }}
          asset_path: ./@tools/Packages/build/HuPHP.phar
          asset_name: HuPHP.phar
          asset_content_type: application/phar
